 -- Banco de dados para a academia TECH FIT
 
 CREATE DATABASE TECH_FIT;
 USE TECH_FIT;
 SELECT TECH_FIT;
 
 
CREATE TABLE EXERCICIOS (
ID_EXERCICIO INT AUTO_INCREMENT PRIMARY KEY,
NOME_EXERCICIO VARCHAR (100) NOT NULL,
DESCRICAO_EXERCICIO VARCHAR (255) NOT NULL,
GRUPO_MUSCULAR VARCHAR (100) NOT NULL,
APARELHO VARCHAR (100) NOT NULL
);

CREATE TABLE AULAS (
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
HORARIO TIME NOT NULL
);

CREATE TABLE FUNCIONARIOS (
  ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY, 
  NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
  LOGIN_REDE VARCHAR(100) GENERATED ALWAYS AS (
    CONCAT(
      SUBSTRING_INDEX(NOME_FUNCIONARIO, '_', 1),
      SUBSTRING_INDEX(NOME_FUNCIONARIO, '_', -1)
    )
  ) STORED,
  NASCIMENTO_FUNCIONARIO DATE NOT NULL,
  CPF_FUNCIONARIO VARCHAR(14) NOT NULL,
  TELEFONE_FUNCIONARIO VARCHAR(15) NOT NULL,
  DATA_ADMISSAO DATE NOT NULL,
  SALARIO DECIMAL(10, 2) NOT NULL,
  CARGO VARCHAR(100) NOT NULL,
  ENDERECO_FUNCIONARIO VARCHAR(255) NOT NULL,
  TURNO CHAR(10) NOT NULL,
  ID_MODALIDADE INT, 
  FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE)
);

CREATE TABLE PLANOS (
ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
NOME_PLANO VARCHAR (100) NOT NULL,
VALOR DECIMAL (4, 2) NOT NULL,
BENEFICIOS VARCHAR (255) NOT NULL
);

CREATE TABLE ALUNOS (
ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (100) NOT NULL,
ENDERECO VARCHAR (255) NOT NULL,
NASCIMENTO DATETIME NOT NULL,
TELEFONE VARCHAR (15) NOT NULL,
CPF VARCHAR (14) NOT NULL,
SEXO VARCHAR (20) NOT NULL,
EMAIL VARCHAR (255) NOT NULL,
SENHA VARCHAR (255) NOT NULL,
STATUS_ALUNO CHAR (10) DEFAULT ("ATIVO"),
ID_PLANO INT,
FOREIGN KEY (ID_PLANO) REFERENCES PLANOS (ID_PLANO)
);

CREATE TABLE PAGAMENTOS(
TIPO_PAGAMENTO VARCHAR (20) NOT NULL,
VALOR_PAGAMENTO DECIMAL (7, 2) NOT NULL,
DATA_PAGAMENTO DATE NOT NULL,
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
ID_ALUNO INT,
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
);


CREATE TABLE UNIDADES (
NOME_UNIDADE VARCHAR (100) NOT NULL,
ENDERECO_UNIDADE VARCHAR (255) NOT NULL,
ID_UNIDADE INT AUTO_INCREMENT PRIMARY KEY,
ID_FUNCIONARIO INT,
ID_ALUNO INT,
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO),
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
);


CREATE TABLE MODALIDADES (
NOME_MODALIDADE VARCHAR (100) NOT NULL,
DESCRICAO_MODALIDADE VARCHAR (255) NOT NULL,
ID_MODALIDADE INT AUTO_INCREMENT PRIMARY KEY,
ID_FUNCIONARIO INT,
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
);

CREATE TABLE PERTENCE (
ID_UNIDADE INT,
ID_ALUNO INT,
FOREIGN KEY(ID_UNIDADE) REFERENCES UNIDADES (ID_UNIDADE),
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
);

CREATE TABLE PARTICIPAM (
ID_AULA INT,
ID_ALUNO INT,
FOREIGN KEY(ID_AULA) REFERENCES AULAS (ID_AULA),
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
);

CREATE TABLE INSCRITOS (
ID_MODALIDADE INT,
ID_ALUNO INT,
FOREIGN KEY(ID_MODALIDADE) REFERENCES MODALIDADES (ID_MODALIDADE),
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
);

CREATE TABLE TEM (
ID_MODALIDADE INT,
ID_FUNCIONARIO INT,
FOREIGN KEY(ID_MODALIDADE) REFERENCES MODALIDADES (ID_MODALIDADE)
);

