-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE EXERCICIOS (
ID_EXERCICIO INT AUTO_INCREMENT PRIMARY KEY,
NOME_EXERCICIO VARCHAR (100) NOT NULL,
DESCRICAO_EXERCICIO VARCHAR (255) NOT NULL,
GRUPO_MUSCULAR VARCHAR (100) NOT NULL,
APARELHO VARCHAR (100) NOT NULL
);

CREATE TABLE FUNCIONARIOS (
NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
NASCIMENTO_FUNCIONARIO  DATE NOT NULL,
CPF_FUNCIONARIO VARCHAR (14) NOT NULL,
TELEFONE_FUNCIONARIO VARCHAR (15) NOT NULL,
DATA_ADMISSAO DATE  NOT NULL,
SALARIO DECIMAL (10, 2) NOT NULL,
CARGO VARCHAR (100) NOT NULL,
ENDERECO_FUNCIONARIO VARCHAR (255) NOT NULL,
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
ID_AULA INT 
);

CREATE TABLE PLANOS (
ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
NOME_PLANO VARCHAR (100) NOT NULL,
VALOR DECIMAL (4, 2) NOT NULL,
BENEFICIOS VARCHAR (100) NOT NULL,
ID_ALUNO INT AUTO_INCREMENT
);

CREATE TABLE UNIDADES (
NOME_UNIDADE VARCHAR (100) NOT NULL,
ENDERECO_UNIDADE VARCHAR (255) NOT NULL,
ID_UNIDADE INT AUTO_INCREMENT PRIMARY KEY,
ID_FUNCIONARIO INT,
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
);

CREATE TABLE PAGAMENTOS (
TIPO_PAGAMENTO VARCHAR (20) NOT NULL,
VALOR_PAGAMENTO DECIMAL (7, 2) NOT NULL,
DATA_PAGAMENTO DATE NOT NULL,
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE AULAS (
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
HORARIO TIME NOT NULL
);

CREATE TABLE ALUNOS (
ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (100) NOT NULL,
ENDERECO VARCHAR (255) NOT NULL,
NASCIMENTO DATE NOT NULL,
TELEFONE VARCHAR (15) NOT NULL,
CPF VARCHAR (14) NOT NULL,
SEXO VARCHAR (20) NOT NULL,
EMAIL VARCHAR (255) NOT NULL,
SENHA VARCHAR (255) NOT NULL,
ID_PAGAMENTO INT AUTO_INCREMENT,
FOREIGN KEY(ID_PAGAMENTO) REFERENCES PAGAMENTOS (ID_PAGAMENTO)
);

CREATE TABLE MODALIDADES (
NOME_MODALIDADE VARCHAR (100) NOT NULL,
DESCRICAO_MODALIDADE VARCHAR (255) NOT NULL,
ID_MODALIDADE INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PERTENCE (
ID_UNIDADE INT AUTO_INCREMENT,
ID_ALUNO INT AUTO_INCREMENT,
FOREIGN KEY(ID_UNIDADE) REFERENCES UNIDADES (ID_UNIDADE),
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
);

CREATE TABLE PARTICIPAM (
ID_AULA INT AUTO_INCREMENT,
ID_ALUNO INT AUTO_INCREMENT,
FOREIGN KEY(ID_AULA) REFERENCES AULAS (ID_AULA),
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
);

CREATE TABLE INSCRITOS (
ID_MODALIDADE INT AUTO_INCREMENT,
ID_ALUNO INT AUTO_INCREMENT,
FOREIGN KEY(ID_MODALIDADE) REFERENCES MODALIDADES (ID_MODALIDADE),
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO)
);

CREATE TABLE TEM (
ID_MODALIDADE INT AUTO_INCREMENT,
ID_FUNCIONARIO INT AUTO_INCREMENT,
FOREIGN KEY(ID_MODALIDADE) REFERENCES MODALIDADES (ID_MODALIDADE)/*falha: chave estrangeira*/
);

ALTER TABLE FUNCIONARIOS ADD FOREIGN KEY(ID_AULA) REFERENCES AULAS (ID_AULA);
ALTER TABLE PLANOS ADD FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS (ID_ALUNO);
