--------------------------------------------------------------
-- Banco de dados: tech_fit
-- Created by: Henrique e Diogo
--------------------------------------------------------------
DROP DATABASE IF EXISTS tech_fit;
CREATE DATABASE tech_fit CHARACTER SET = utf8mb4; -- Determina a linguagem a ser ultilizada no banco de dados
USE tech_fit; 

-- planos
DROP TABLE IF EXISTS PLANOS;
CREATE TABLE PLANOS( 
ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
NOME_PLANO VARCHAR(100) NOT NULL UNIQUE, -- UNIQUE É PARA DETERMINAR QUE O NOME DO PLANO É UNICO
VALOR DECIMAL(8,2) NOT NULL,
BENEFICIOS VARCHAR(1000) DEFAULT NULL,
DURACAO_MES SMALLINT UNSIGNED NOT NULL DEFAULT 1, -- SMALLINT SERVE PARA COLCOARMOS NÚMEROS INTEIROS PEQUENOS
CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

-- ALUNOS
DROP TABLE IF EXISTS ALUNOS;
CREATE TABLE ALUNOS (
  ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(150) NOT NULL,
  ENDERECO VARCHAR(500),
  NASCIMENTO DATE NOT NULL,
  TELEFONE VARCHAR(20),
  CPF VARCHAR(14) NOT NULL UNIQUE,
  SEXO ENUM('MASCULINO','FEMININO','OUTRO','NAO_DECLARAR') DEFAULT 'NAO_DECLARAR',
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  SENHA_HASH VARCHAR(255) NOT NULL,
  STATUS_ALUNO ENUM('ATIVO','INATIVO','SUSPENSO') NOT NULL DEFAULT 'ATIVO',
  ID_PLANO INT NOT NULL,
  CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_alunos_plano (ID_PLANO), -- INDEX SERVE PARA BUSCAR MAIS RÁPDIO
  CONSTRAINT fk_alunos_planos FOREIGN KEY (ID_PLANO) REFERENCES PLANOS(ID_PLANO));
  
-- FUNCIONÁRIOS
DROP TABLE IF EXISTS FUNCIONARIOS;
CREATE TABLE FUNCIONARIOS (
  ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
  NOME_FUNCIONARIO VARCHAR(150) NOT NULL,
  LOGIN_REDE VARCHAR(255) NOT NULL,
  NASCIMENTO_FUNCIONARIO DATE NOT NULL,
  CPF_FUNCIONARIO VARCHAR(14) NOT NULL UNIQUE,
  TELEFOHNE_FUNCIONARIO VARCHAR(20),
  DATA_ADMISSAO DATE NOT NULL,
  SALARIO DECIMAL(10,2) NOT NULL CHECK (SALARIO >= 0),
  CARGO VARCHAR(80) NOT NULL,
  ENDERECO_FUNCIONARIO VARCHAR(500),
  EMAIL_FUNCIONARIO VARCHAR(100) NOT NULL UNIQUE UNIQUE,
  SENHA_FUNCIONARIO VARCHAR(255),
  TURNO ENUM('MANHA','TARDE','NOITE','ROTATIVO') DEFAULT 'ROTATIVO',
  ID_MODALIDADE INT DEFAULT NULL);
  
  
  
-- UNIDADES
DROP TABLE IF EXISTS UNIDADES;
CREATE TABLE UNIDADES (
  ID_UNIDADE INT AUTO_INCREMENT PRIMARY KEY,
  NOME_UNIDADE VARCHAR(120) NOT NULL,
  ENDERECO_UNIDADE VARCHAR(500) NOT NULL UNIQUE,
  TELEFONE_UNIDADE VARCHAR(20),
  ID_GERENTE INT DEFAULT NULL,
  CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
  
  select * from unidades;
  
-- EXERCÍCIOS
DROP TABLE IF EXISTS MODALIDADES;
CREATE TABLE MODALIDADES (
  ID_MODALIDADE INT AUTO_INCREMENT PRIMARY KEY,
  NOME_MODALIDADE VARCHAR(120) NOT NULL,
  DESCRICAO_MODALIDADE VARCHAR(1000),
  CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_modalidades_nome (NOME_MODALIDADE)
);
	
    select * from modalidades;


-- AULAS
DROP TABLE IF EXISTS AULAS;
CREATE TABLE AULAS (
  ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
  NOME_AULA VARCHAR(150),
  ID_MODALIDADE INT NOT NULL,
  ID_INSTRUTOR INT DEFAULT NULL,
  ID_UNIDADE INT DEFAULT NULL,
  DIA_SEMANA ENUM('DOM','SEG','TER','QUA','QUI','SEX','SAB') NOT NULL,
  HORARIO_INICIO TIME NOT NULL,
  DURACAO_MINUTOS SMALLINT UNSIGNED NOT NULL DEFAULT 60,
  VAGAS SMALLINT UNSIGNED NOT NULL DEFAULT 30,
  CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_aulas_modalidade (ID_MODALIDADE),
  INDEX idx_aulas_instrutor (ID_INSTRUTOR),
  INDEX idx_aulas_unidade (ID_UNIDADE),
  CONSTRAINT fk_aulas_modalidade FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_aulas_instrutor FOREIGN KEY (ID_INSTRUTOR) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_aulas_unidade FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES(ID_UNIDADE));
  
  -- PAGAMENTO
  DROP TABLE IF EXISTS PAGAMENTOS;
CREATE TABLE PAGAMENTOS (
  ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
  ID_ALUNO INT NOT NULL,
  TIPO_PAGAMENTO ENUM('DINHEIRO','CREDITO', 'DEBITO','PIX') NOT NULL,
  VALOR_PAGAMENTO DECIMAL(10,2) NOT NULL CHECK (VALOR_PAGAMENTO >= 0),
  DATA_PAGAMENTO DATE NOT NULL,
  CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_pagamentos_aluno (ID_ALUNO),
  CONSTRAINT fk_pagamentos_alunos FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO)
    ON UPDATE CASCADE ON DELETE RESTRICT);
    
-- PERTENCE
DROP TABLE IF EXISTS PERTENCE;
CREATE TABLE PERTENCE (
  ID_UNIDADE INT NOT NULL,
  ID_ALUNO INT NOT NULL,
  DATA_INSCRICAO DATE NOT NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (ID_UNIDADE, ID_ALUNO),
  INDEX idx_pertence_aluno (ID_ALUNO),
  CONSTRAINT fk_pertence_unidade FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADES(ID_UNIDADE),
  CONSTRAINT fk_pertence_aluno FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO));
  
  -- PARTICIPAM
  DROP TABLE IF EXISTS PARTICIPAM;
CREATE TABLE PARTICIPAM (
  ID_AULA INT NOT NULL,
  ID_ALUNO INT NOT NULL,
  DATA_PARTICIPACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_AULA, ID_ALUNO),
  INDEX idx_participam_aluno (ID_ALUNO),
  CONSTRAINT fk_participam_aula FOREIGN KEY (ID_AULA) REFERENCES AULAS(ID_AULA),
  CONSTRAINT fk_participam_aluno FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO));
  
  -- INSCRITOS
  DROP TABLE IF EXISTS INSCRITOS;
CREATE TABLE INSCRITOS (
  ID_MODALIDADE INT NOT NULL,
  ID_ALUNO INT NOT NULL,
  DATA_INSCRICAO DATE NOT NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (ID_MODALIDADE, ID_ALUNO),
  INDEX idx_inscritos_aluno (ID_ALUNO),
  CONSTRAINT fk_inscritos_modalidade FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE),
  CONSTRAINT fk_inscritos_aluno FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO));
  
-- TEM
DROP TABLE IF EXISTS  TEM;
CREATE TABLE TEM (
  ID_MODALIDADE INT NOT NULL,
  ID_FUNCIONARIO INT NOT NULL,
  DATA_ATUACAO DATE DEFAULT (CURRENT_DATE),
  PRIMARY KEY (ID_MODALIDADE, ID_FUNCIONARIO),
  INDEX idx_tem_funcionario (ID_FUNCIONARIO),
  CONSTRAINT fk_tem_modalidade FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE),
  CONSTRAINT fk_tem_funcionario FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO));
  
  

  


